### ISSUE TITLE
[Protocol] Python implementation

### ISSUE THREAD

**Issue by syncu2** [Splamy/TS3AudioBot#173]
Hello there,

I got no actual issue with the bot, but a related question: I am currently trying to implement a small TS client in Python based on your [protocol description](https://github.com/Splamy/TS3AudioBot/blob/0d1d081c2eb465743efd8cbf36ec57addc9178db/TS3Client/ts3protocol.md)  (awesome work, btw). 

Everything works as expected, until step 2.4. After submitting the clientinitiv message, i get an encrypted packet from the server, which I am not able to decrypt with the default key/nonce from your protocol documentation. The MAC check fails, and even if I ignore the MAC check, the decrypted text seems to be incorrect.

This is the function I use to parse all the packets. The payload parameter contains the whole packet including MAC and header. payload[x:y] denotes the part of the packet from byte x to (not including) byte y. 

```
def parse_packet(payload, key=None, nonce=None):
	res = {
		'mac':		bytes(payload[0:8]),
		'pid':		struct.unpack('>H', payload[8:10])[0],
		'tp':		struct.unpack('B', payload[10:11])[0] & 15,
		'flag_u':   (struct.unpack('B', payload[10:11])[0] & (1 << 7)) >> 7,
		'flag_c':   (struct.unpack('B', payload[10:11])[0] & (1 << 6)) >> 6,
		'flag_n':   (struct.unpack('B', payload[10:11])[0] & (1 << 5)) >> 5,
		'flag_f':   (struct.unpack('B', payload[10:11])[0] & (1 << 4)) >> 4,
		'payload':	payload[11:]
	}

        # check if packet needs to be decrypted
	if res['flag_u'] == 0:
		if key == None:
                        # Default key/nonce
			key = bytes(bytearray([0x63, 0x3A, 0x5C, 0x77, 0x69, 0x6E, 0x64, 0x6F, 0x77, 0x73, 0x5C, 0x73, 0x79, 0x73, 0x74, 0x65]))
			nonce = bytes(bytearray([0x6D, 0x5C, 0x66, 0x69, 0x72, 0x65, 0x77, 0x61, 0x6C, 0x6C, 0x33, 0x32, 0x2E, 0x63, 0x70, 0x6C]))

		cipher = AES.new(key, AES.MODE_EAX, nonce=nonce, mac_len=8)

                # this fails:
		res['payload'] = cipher.decrypt_and_verify(res['payload'], res['mac'])

	return res
```

I am using the PyCryptodome library for crypto, [see documentation here](http://pycryptodome.readthedocs.io/en/latest/src/examples.html).

What am I doing wrong? I tried looking at the code of the audio bot, but the BouncyCastle libraries are very poorly documented, so I don't understand what is going on at the interesting points.

Thank you

==============================

EDIT: To verify that the encryption is correct, here is an example (base64) ciphertext and MAC for plaintext "abcdefg":

```
key = bytes(bytearray([0x63, 0x3A, 0x5C, 0x77, 0x69, 0x6E, 0x64, 0x6F, 0x77, 0x73, 0x5C, 0x73, 0x79, 0x73, 0x74, 0x65]))
nonce = bytes(bytearray([0x6D, 0x5C, 0x66, 0x69, 0x72, 0x65, 0x77, 0x61, 0x6C, 0x6C, 0x33, 0x32, 0x2E, 0x63, 0x70, 0x6C]))

cipher = AES.new(key, AES.MODE_EAX, nonce=nonce, mac_len=8)
ciphertext, mac = cipher.encrypt_and_digest(b'abcdefg')

print(base64.b64encode(ciphertext))
print(base64.b64encode(mac))

```

Output:

```
n3qBRKFp4Q==
gu8lzzveD9A=
```

**Comment by syncu2** [comment]
Ok, I found the issue. 
You need to execute

```
cipher.update(payload[8:11])
```
before decrypting, because the 3 header bytes are considered "associated data" which is not encrypted but also authenticated.

**Comment by syncu2** [comment]
I noticed two problems regarding compression:

1. For compressed (+ fragmented?) packets, the MAC check fails. I can decrypt them with the key and nonce and the plaintext seems to be correct, but the MAC is not.
2. The decompression does not yet work for me. The decrypted payload I get from the server starts like this:
```
b'G\xe8\x02\x00\x00\x0f\x05\x00\x00\x00\x00\x04\x80initserver virtualT%_name=Admin\x00\x02\x00\x80Official}\x0bwelcomemessage=Room\'...
```
(all compressed payloads start with 'G'). However if I try to decompress it with the QuickLZ library, I get a segfault in Python and an ArrayOutOfBoundsException in Java. Does the implementation used by Teamspeak and in your audio bot differ from the official QuickLZ implementation? Is it some special version?

**Comment by Splamy** [comment]
I recommend you to use the protocol.md on the develop branch as some mistakes are fixed there (like the wrongly stated compression level).
Regarding the other quesion, I'll write tomorrow since I'm off for now...

**Comment by syncu2** [comment]
Alright, thank you. 
Regarding the decompression problem, I think it's only some minor (padding?) issue, because if I try decompressing my string in Java and add some debug output to the QuickLZ code to see the intermediate results, I see almost the correct string, but close to the end, it always fails. Need to do more experiments today...

**Comment by syncu2** [comment]
Ok, just solved the issue with the MAC check. I was only reading 256 bytes per packet, cutting off the end. However, the decompression problem persists. I will give you an example of a decrypted but compressed string I get from the server. (The teamspeak server is 79.133.54.198:9234 in case you want to test it yourself). It is the initserver message from chapter 3.4 in your protocol documentation.

Base64 encoded:
```
R3EDAAA4BQAAAAAEgGluaXRzZXJ2ZXIgdmlydHVhbFQlX25hbWU9VEFOWlZFAAAQgFJCT1Q6XHNQdWJsaWNcc0NvbW11geJ5XHNUZWFtU3BlAAAAgWFrXHNccFxzWW91VHViZSxcc2hpdGJveJGxVHdpdGNoAYAAwH0Ld2VsY29tZW1lc3NhZ2V9C3BsYXRmb3JtPUxpbnV4fQsBAECAASVzaW9uPTMuMC4xMy44XHNbQnVpbGTxsDE1MDA0NTI4CIABgDExXX0LbWF4Y2xpZW50cz1hM30LY3JlYXRlZD0xNDcxMzQQAJKQNDQyNX4Lb2RlY19lbmNyeXB08ZhfbZEjPTJ9C2hvc3S1JT1bAAAAiGJdRmFsbHNcc1tjb2xvcj1yZWRddHMudGFuegElYm90QAAAgC5ldVtcL1OaXVxzYmVpXHNlaW5lbVxzRXVyZXJcc0t1SABAiG1wZbJqb2QienNvXHNuaWNodFxzZnVuayL4aWVydJGxZGFuAEBggm5cc2RpZXNlXHNJUFxzASV3ZW5kZW7xsNlaNznRITMuNTQuABcggDE5ODo5MjM05+pwCxqUujF9C2RlZmF1bHRfVSVncm91cD00NjcSYUHEN3ALF2NocYhlbF8ESTIxOTZ9C+KFYnKIcl91cmxwCxpnZniAJyJpbnQhUBCAgMBhbD0wfQtwcmlvcml0eV9zYjZlcl9kaW1tkrppZmljYXSBG4BgAOAtMTguMDAwLnVpZD0yMT5144V1dHRvbl90b29sdGlwPfWAsXb7oDiA5HixQ2+xtQhbfQvphSFLPXlvdXQxQi5Rm1wvdHeccAsaFR49aHR0cDpcL1wAgwCAL3d3dy5wbmdxqoRdd3AtY2+RI250XC91cGxvYWRzXC8yMAADBocxNlwvMDdcL/GAMjUtUE5HLUltcRPhKjB4MTgwkmx9C4J7X3Bob6DGoYBuZXRpY30LaVGYX/F7L3VwPTDRLCHTfQthc2tfAYRfcU52aWxlZ2Vr/ADIgWV57yPjhXSIs5IudVbndGVtcF9kZWxldGWSIGF5kSADY+EjYWNuPWFsaAAwgG1hbiEGYVGvcec1MSBwdj02IGx0PTEgUa8xkl90YWxrX3BvdwwEAIBlcuEjVa9uZWVkZWSFUHF1ZXJ5X3ZpZXdfcG93ZXI9NzU=
```

Python binary string notation:
```
Gq\x03\x00\x008\x05\x00\x00\x00\x00\x04\x80initserver virtualT%_name=TANZVE\x00\x00\x10\x80RBOT:\\sPublic\\sCommu\x81\xe2y\\sTeamSpe\x00\x00\x00\x81ak\\s\\p\\sYouTube,\\shitbox\x91\xb1Twitch\x01\x80\x00\xc0}\x0bwelcomemessage}\x0bplatform=Linux}\x0b\x01\x00@\x80\x01%sion=3.0.13.8\\s[Build\xf1\xb015004528\x08\x80\x01\x8011]}\x0bmaxclients=a3}\x0bcreated=147134\x10\x00\x92\x904425~\x0bodec_encrypt\xf1\x98_m\x91#=2}\x0bhost\xb5%=[\x00\x00\x00\x88b]Falls\\s[color=red]ts.tanz\x01%bot@\x00\x00\x80.eu[\\/S\x9a]\\sbei\\seinem\\sEurer\\sKuH\x00@\x88mpe\xb2jod"zso\\snicht\\sfunk"\xf8iert\x91\xb1dan\x00@`\x82n\\sdiese\\sIP\\s\x01%wenden\xf1\xb0\xd9Z79\xd1!3.54.\x00\x17 \x80198:9234\xe7\xeap\x0b\x1a\x94\xba1}\x0bdefault_U%group=467\x12aA\xc47p\x0b\x17chq\x88el_\x04I2196}\x0b\xe2\x85br\x88r_urlp\x0b\x1agfx\x80\'"int!P\x10\x80\x80\xc0al=0}\x0bpriority_sb6er_dimm\x92\xbaificat\x81\x1b\x80`\x00\xe0-18.000.uid=21>u\xe3\x85utton_tooltip=\xf5\x80\xb1v\xfb\xa08\x80\xe4x\xb1Co\xb1\xb5\x08[}\x0b\xe9\x85!K=yout1B.Q\x9b\\/tw\x9cp\x0b\x1a\x15\x1e=http:\\/\\\x00\x83\x00\x80/www.pngq\xaa\x84]wp-co\x91#nt\\/uploads\\/20\x00\x03\x06\x8716\\/07\\/\xf1\x8025-PNG-Imq\x13\xe1*0x180\x92l}\x0b\x82{_pho\xa0\xc6\xa1\x80netic}\x0biQ\x98_\xf1{/up=0\xd1,!\xd3}\x0bask_\x01\x84_qNvilegek\xfc\x00\xc8\x81ey\xef#\xe3\x85t\x88\xb3\x92.uV\xe7temp_delete\x92 ay\x91 \x03c\xe1#acn=alh\x000\x80man!\x06aQ\xafq\xe751 pv=6 lt=1 Q\xaf1\x92_talk_pow\x0c\x04\x00\x80er\xe1#U\xafneeded\x85Pquery_view_power=75
```

I always get a segfault / array bounds exception when trying to decompress it.

**Comment by Splamy** [comment]
```
var data = Convert.FromBase64String("R3EDAAA4BQAAAAAEgGluaXRzZXJ2ZXIgdmlydHVhbFQlX25hbWU9VEFOWlZFAAAQgFJCT1Q6XHNQdWJsaWNcc0NvbW11geJ5XHNUZWFtU3BlAAAAgWFrXHNccFxzWW91VHViZSxcc2hpdGJveJGxVHdpdGNoAYAAwH0Ld2VsY29tZW1lc3NhZ2V9C3BsYXRmb3JtPUxpbnV4fQsBAECAASVzaW9uPTMuMC4xMy44XHNbQnVpbGTxsDE1MDA0NTI4CIABgDExXX0LbWF4Y2xpZW50cz1hM30LY3JlYXRlZD0xNDcxMzQQAJKQNDQyNX4Lb2RlY19lbmNyeXB08ZhfbZEjPTJ9C2hvc3S1JT1bAAAAiGJdRmFsbHNcc1tjb2xvcj1yZWRddHMudGFuegElYm90QAAAgC5ldVtcL1OaXVxzYmVpXHNlaW5lbVxzRXVyZXJcc0t1SABAiG1wZbJqb2QienNvXHNuaWNodFxzZnVuayL4aWVydJGxZGFuAEBggm5cc2RpZXNlXHNJUFxzASV3ZW5kZW7xsNlaNznRITMuNTQuABcggDE5ODo5MjM05+pwCxqUujF9C2RlZmF1bHRfVSVncm91cD00NjcSYUHEN3ALF2NocYhlbF8ESTIxOTZ9C+KFYnKIcl91cmxwCxpnZniAJyJpbnQhUBCAgMBhbD0wfQtwcmlvcml0eV9zYjZlcl9kaW1tkrppZmljYXSBG4BgAOAtMTguMDAwLnVpZD0yMT5144V1dHRvbl90b29sdGlwPfWAsXb7oDiA5HixQ2+xtQhbfQvphSFLPXlvdXQxQi5Rm1wvdHeccAsaFR49aHR0cDpcL1wAgwCAL3d3dy5wbmdxqoRdd3AtY2+RI250XC91cGxvYWRzXC8yMAADBocxNlwvMDdcL/GAMjUtUE5HLUltcRPhKjB4MTgwkmx9C4J7X3Bob6DGoYBuZXRpY30LaVGYX/F7L3VwPTDRLCHTfQthc2tfAYRfcU52aWxlZ2Vr/ADIgWV57yPjhXSIs5IudVbndGVtcF9kZWxldGWSIGF5kSADY+EjYWNuPWFsaAAwgG1hbiEGYVGvcec1MSBwdj02IGx0PTEgUa8xkl90YWxrX3BvdwwEAIBlcuEjVa9uZWVkZWSFUHF1ZXJ5X3ZpZXdfcG93ZXI9NzU=");
var dec = QuickerLz.Decompress(data, maxSize: 8192);
> System.Text.Encoding.UTF8.GetString(dec)
"initserver virtualserver_name=TANZVERBOT:\sPublic\sCommunity\sTeamSpeak\s\p\sYouTube,\shitbox,\sTwitch virtualserver_welcomemessage virtualserver_platform=Linux virtualserver_version=3.0.13.8\s[Build:\s1500452811] virtualserver_maxclients=500 virtualserver_created=1471344425 virtualserver_codec_encryption_mode=2 virtualserver_hostmessage=[b]Falls\s[color=red]ts.tanzverbot.eu[\/color]\sbei\seinem\sEurer\sKumpels\soder\sso\snicht\sfunktioniert,\sdann\sdiese\sIP\sverwenden:\s[color=red]79.133.54.198:9234[\/color] virtualserver_hostmessage_mode=1 virtualserver_default_server_group=4677 virtualserver_default_channel_group=2196 virtualserver_hostbanner_url virtualserver_hostbanner_gfx_url virtualserver_hostbanner_gfx_interval=0 virtualserver_priority_speaker_dimm_modificator=-18.0000 virtualserver_id=211 virtualserver_hostbutton_tooltip=YouTube\sChannel\svon\sTANZVERBOT virtualserver_hostbutton_url=youtube.com\/tanzverbot virtualserver_hostbutton_gfx_url=http:\/\/www.pngall.com\/wp-content\/uploads\/2016\/07\/Youtube-PNG-Image-180x180.png virtualserver_name_phonetic virtualserver_icon_id=0 virtualserver_ip=0.0.0.0 virtualserver_ask_for_privilegekey=0 virtualserver_hostbanner_mode=0 virtualserver_channel_temp_delete_delay_default=0 acn=almaner aclid=151 pv=6 lt=1 client_talk_power=0 client_needed_serverquery_view_power=75"
> 
```
Maybe your quicklz imlementation is faulty ?

**Comment by syncu2** [comment]
Ok, just tested again with the Java version and it worked... all python libraries I tested seem to be corrupted.  Guess I have to translate the Java implementation to Python myself.

Thanks for your help!

**Comment by Splamy** [comment]
https://github.com/ReSpeak/quicklz/blob/master/Format.md if you need any guidance we also have a qlz format paper :)
